"""initial schema

Revision ID: 1e63639da8e0
Revises:
Create Date: 2026-08-18 17:13:27.359737+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import studyforge.models.base

revision: str = "1e63639da8e0"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "courses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("archived_at", studyforge.models.base.UTCDateTime(), nullable=True),
        sa.Column("created_at", studyforge.models.base.UTCDateTime(), nullable=False),
        sa.Column("updated_at", studyforge.models.base.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_courses")),
    )
    with op.batch_alter_table("courses", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_courses_archived_at"), ["archived_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_courses_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_courses_name"), ["name"], unique=False)

    op.create_table(
        "documents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum("PASTE", "UPLOAD", name="documentsource", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "EXTRACTED",
                "NO_TEXT",
                "FAILED",
                name="documentstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("original_filename", sa.String(length=255), nullable=True),
        sa.Column("stored_filename", sa.String(length=255), nullable=True),
        sa.Column("content_type", sa.String(length=100), nullable=True),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("extracted_text", sa.Text(), nullable=True),
        sa.Column("char_count", sa.Integer(), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("extraction_error", sa.Text(), nullable=True),
        sa.Column("created_at", studyforge.models.base.UTCDateTime(), nullable=False),
        sa.Column("updated_at", studyforge.models.base.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_documents_course_id_courses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
    )
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_documents_course_id"), ["course_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_documents_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_documents_sha256"), ["sha256"], unique=False)
        batch_op.create_index(batch_op.f("ix_documents_status"), ["status"], unique=False)

    op.create_table(
        "quizzes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column(
            "generation_method",
            sa.Enum(
                "MANUAL",
                "DETERMINISTIC",
                "AI",
                name="generationmethod",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("ai_provider", sa.String(length=50), nullable=True),
        sa.Column("ai_model", sa.String(length=100), nullable=True),
        sa.Column("created_at", studyforge.models.base.UTCDateTime(), nullable=False),
        sa.Column("updated_at", studyforge.models.base.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_quizzes_course_id_courses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quizzes")),
    )
    with op.batch_alter_table("quizzes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_quizzes_course_id"), ["course_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_quizzes_created_at"), ["created_at"], unique=False)

    op.create_table(
        "study_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=True),
        sa.Column("started_at", studyforge.models.base.UTCDateTime(), nullable=False),
        sa.Column("ended_at", studyforge.models.base.UTCDateTime(), nullable=True),
        sa.Column("cards_reviewed", sa.Integer(), nullable=False),
        sa.Column("again_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_study_sessions_course_id_courses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_study_sessions")),
    )
    with op.batch_alter_table("study_sessions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_study_sessions_course_id"), ["course_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_study_sessions_started_at"), ["started_at"], unique=False
        )

    op.create_table(
        "document_chunks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("char_start", sa.Integer(), nullable=False),
        sa.Column("char_end", sa.Integer(), nullable=False),
        sa.Column("heading", sa.String(length=300), nullable=True),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_document_chunks_document_id_documents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_chunks")),
        sa.UniqueConstraint("document_id", "ordinal", name="uq_document_chunks_ordinal"),
    )
    with op.batch_alter_table("document_chunks", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_document_chunks_document_id"), ["document_id"], unique=False
        )
        batch_op.create_index(
            "ix_document_chunks_document_ordinal", ["document_id", "ordinal"], unique=False
        )

    op.create_table(
        "quiz_attempts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("quiz_id", sa.Integer(), nullable=False),
        sa.Column("started_at", studyforge.models.base.UTCDateTime(), nullable=False),
        sa.Column("completed_at", studyforge.models.base.UTCDateTime(), nullable=True),
        sa.Column("question_count", sa.Integer(), nullable=False),
        sa.Column("correct_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["quiz_id"],
            ["quizzes.id"],
            name=op.f("fk_quiz_attempts_quiz_id_quizzes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quiz_attempts")),
    )
    with op.batch_alter_table("quiz_attempts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_quiz_attempts_quiz_id"), ["quiz_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_quiz_attempts_started_at"), ["started_at"], unique=False
        )

    op.create_table(
        "concepts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("normalized_name", sa.String(length=200), nullable=False),
        sa.Column("definition", sa.Text(), nullable=True),
        sa.Column(
            "extraction_method",
            sa.Enum(
                "MANUAL",
                "DEFINITION",
                "GLOSSARY",
                "HEADING",
                "FREQUENCY",
                "AI",
                name="extractionmethod",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("source_document_id", sa.Integer(), nullable=True),
        sa.Column("source_chunk_id", sa.Integer(), nullable=True),
        sa.Column("created_at", studyforge.models.base.UTCDateTime(), nullable=False),
        sa.Column("updated_at", studyforge.models.base.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_concepts_course_id_courses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_chunk_id"],
            ["document_chunks.id"],
            name=op.f("fk_concepts_source_chunk_id_document_chunks"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_document_id"],
            ["documents.id"],
            name=op.f("fk_concepts_source_document_id_documents"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_concepts")),
        sa.UniqueConstraint("course_id", "normalized_name", name="uq_concepts_course_name"),
    )
    with op.batch_alter_table("concepts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_concepts_course_id"), ["course_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_concepts_created_at"), ["created_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_concepts_normalized_name"), ["normalized_name"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_concepts_score"), ["score"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_concepts_source_document_id"), ["source_document_id"], unique=False
        )

    op.create_table(
        "flashcards",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("concept_id", sa.Integer(), nullable=True),
        sa.Column("front", sa.Text(), nullable=False),
        sa.Column("back", sa.Text(), nullable=False),
        sa.Column(
            "generation_method",
            sa.Enum(
                "MANUAL",
                "DETERMINISTIC",
                "AI",
                name="generationmethod",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("source_document_id", sa.Integer(), nullable=True),
        sa.Column("source_chunk_id", sa.Integer(), nullable=True),
        sa.Column("ai_provider", sa.String(length=50), nullable=True),
        sa.Column("ai_model", sa.String(length=100), nullable=True),
        sa.Column("generated_at", studyforge.models.base.UTCDateTime(), nullable=True),
        sa.Column("suspended_at", studyforge.models.base.UTCDateTime(), nullable=True),
        sa.Column(
            "state",
            sa.Enum(
                "LEARNING", "REVIEW", "RELEARNING", name="cardstate", native_enum=False, length=20
            ),
            nullable=False,
        ),
        sa.Column("step", sa.Integer(), nullable=True),
        sa.Column("stability", sa.Float(), nullable=True),
        sa.Column("difficulty", sa.Float(), nullable=True),
        sa.Column("due_at", studyforge.models.base.UTCDateTime(), nullable=False),
        sa.Column("last_reviewed_at", studyforge.models.base.UTCDateTime(), nullable=True),
        sa.Column("reps", sa.Integer(), nullable=False),
        sa.Column("lapses", sa.Integer(), nullable=False),
        sa.Column("created_at", studyforge.models.base.UTCDateTime(), nullable=False),
        sa.Column("updated_at", studyforge.models.base.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["concept_id"],
            ["concepts.id"],
            name=op.f("fk_flashcards_concept_id_concepts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_flashcards_course_id_courses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_chunk_id"],
            ["document_chunks.id"],
            name=op.f("fk_flashcards_source_chunk_id_document_chunks"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_document_id"],
            ["documents.id"],
            name=op.f("fk_flashcards_source_document_id_documents"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_flashcards")),
    )
    with op.batch_alter_table("flashcards", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_flashcards_concept_id"), ["concept_id"], unique=False)
        batch_op.create_index("ix_flashcards_course_due", ["course_id", "due_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_flashcards_course_id"), ["course_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_flashcards_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_flashcards_due_at"), ["due_at"], unique=False)
        batch_op.create_index(
            "ix_flashcards_due_suspended", ["due_at", "suspended_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_flashcards_source_document_id"), ["source_document_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_flashcards_suspended_at"), ["suspended_at"], unique=False
        )

    op.create_table(
        "questions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("quiz_id", sa.Integer(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "MULTIPLE_CHOICE", "SHORT_ANSWER", name="questionkind", native_enum=False, length=20
            ),
            nullable=False,
        ),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("expected_answer", sa.Text(), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=True),
        sa.Column("choices", sa.JSON(), nullable=True),
        sa.Column("correct_choice_index", sa.Integer(), nullable=True),
        sa.Column("concept_id", sa.Integer(), nullable=True),
        sa.Column("source_document_id", sa.Integer(), nullable=True),
        sa.Column("source_chunk_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["concept_id"],
            ["concepts.id"],
            name=op.f("fk_questions_concept_id_concepts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["quiz_id"],
            ["quizzes.id"],
            name=op.f("fk_questions_quiz_id_quizzes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_chunk_id"],
            ["document_chunks.id"],
            name=op.f("fk_questions_source_chunk_id_document_chunks"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_document_id"],
            ["documents.id"],
            name=op.f("fk_questions_source_document_id_documents"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_questions")),
        sa.UniqueConstraint("quiz_id", "ordinal", name="uq_questions_ordinal"),
    )
    with op.batch_alter_table("questions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_questions_concept_id"), ["concept_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_questions_quiz_id"), ["quiz_id"], unique=False)

    op.create_table(
        "answer_attempts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("quiz_attempt_id", sa.Integer(), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("concept_id", sa.Integer(), nullable=True),
        sa.Column("response", sa.Text(), nullable=False),
        sa.Column("is_correct", sa.Boolean(), nullable=False),
        sa.Column("self_graded", sa.Boolean(), nullable=False),
        sa.Column("answered_at", studyforge.models.base.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["concept_id"],
            ["concepts.id"],
            name=op.f("fk_answer_attempts_concept_id_concepts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
            name=op.f("fk_answer_attempts_question_id_questions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["quiz_attempt_id"],
            ["quiz_attempts.id"],
            name=op.f("fk_answer_attempts_quiz_attempt_id_quiz_attempts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_answer_attempts")),
        sa.UniqueConstraint("quiz_attempt_id", "question_id", name="uq_answer_attempts_question"),
    )
    with op.batch_alter_table("answer_attempts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_answer_attempts_answered_at"), ["answered_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_answer_attempts_concept_id"), ["concept_id"], unique=False
        )
        batch_op.create_index(
            "ix_answer_attempts_concept_time", ["concept_id", "answered_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_answer_attempts_question_id"), ["question_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_answer_attempts_quiz_attempt_id"), ["quiz_attempt_id"], unique=False
        )

    op.create_table(
        "reviews",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("flashcard_id", sa.Integer(), nullable=False),
        sa.Column("study_session_id", sa.Integer(), nullable=True),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("reviewed_at", studyforge.models.base.UTCDateTime(), nullable=False),
        sa.Column("elapsed_days", sa.Integer(), nullable=True),
        sa.Column("scheduled_days", sa.Integer(), nullable=False),
        sa.Column(
            "state_before",
            sa.Enum(
                "LEARNING", "REVIEW", "RELEARNING", name="cardstate", native_enum=False, length=20
            ),
            nullable=False,
        ),
        sa.Column(
            "state_after",
            sa.Enum(
                "LEARNING", "REVIEW", "RELEARNING", name="cardstate", native_enum=False, length=20
            ),
            nullable=False,
        ),
        sa.Column("stability_before", sa.Float(), nullable=True),
        sa.Column("stability_after", sa.Float(), nullable=True),
        sa.Column("difficulty_before", sa.Float(), nullable=True),
        sa.Column("difficulty_after", sa.Float(), nullable=True),
        sa.Column("retrievability_before", sa.Float(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["flashcard_id"],
            ["flashcards.id"],
            name=op.f("fk_reviews_flashcard_id_flashcards"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["study_session_id"],
            ["study_sessions.id"],
            name=op.f("fk_reviews_study_session_id_study_sessions"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reviews")),
    )
    with op.batch_alter_table("reviews", schema=None) as batch_op:
        batch_op.create_index("ix_reviews_card_time", ["flashcard_id", "reviewed_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_reviews_flashcard_id"), ["flashcard_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_reviews_reviewed_at"), ["reviewed_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_reviews_study_session_id"), ["study_session_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("reviews", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_reviews_study_session_id"))
        batch_op.drop_index(batch_op.f("ix_reviews_reviewed_at"))
        batch_op.drop_index(batch_op.f("ix_reviews_flashcard_id"))
        batch_op.drop_index("ix_reviews_card_time")

    op.drop_table("reviews")
    with op.batch_alter_table("answer_attempts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_answer_attempts_quiz_attempt_id"))
        batch_op.drop_index(batch_op.f("ix_answer_attempts_question_id"))
        batch_op.drop_index("ix_answer_attempts_concept_time")
        batch_op.drop_index(batch_op.f("ix_answer_attempts_concept_id"))
        batch_op.drop_index(batch_op.f("ix_answer_attempts_answered_at"))

    op.drop_table("answer_attempts")
    with op.batch_alter_table("questions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_questions_quiz_id"))
        batch_op.drop_index(batch_op.f("ix_questions_concept_id"))

    op.drop_table("questions")
    with op.batch_alter_table("flashcards", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_flashcards_suspended_at"))
        batch_op.drop_index(batch_op.f("ix_flashcards_source_document_id"))
        batch_op.drop_index("ix_flashcards_due_suspended")
        batch_op.drop_index(batch_op.f("ix_flashcards_due_at"))
        batch_op.drop_index(batch_op.f("ix_flashcards_created_at"))
        batch_op.drop_index(batch_op.f("ix_flashcards_course_id"))
        batch_op.drop_index("ix_flashcards_course_due")
        batch_op.drop_index(batch_op.f("ix_flashcards_concept_id"))

    op.drop_table("flashcards")
    with op.batch_alter_table("concepts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_concepts_source_document_id"))
        batch_op.drop_index(batch_op.f("ix_concepts_score"))
        batch_op.drop_index(batch_op.f("ix_concepts_normalized_name"))
        batch_op.drop_index(batch_op.f("ix_concepts_created_at"))
        batch_op.drop_index(batch_op.f("ix_concepts_course_id"))

    op.drop_table("concepts")
    with op.batch_alter_table("quiz_attempts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_quiz_attempts_started_at"))
        batch_op.drop_index(batch_op.f("ix_quiz_attempts_quiz_id"))

    op.drop_table("quiz_attempts")
    with op.batch_alter_table("document_chunks", schema=None) as batch_op:
        batch_op.drop_index("ix_document_chunks_document_ordinal")
        batch_op.drop_index(batch_op.f("ix_document_chunks_document_id"))

    op.drop_table("document_chunks")
    with op.batch_alter_table("study_sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_study_sessions_started_at"))
        batch_op.drop_index(batch_op.f("ix_study_sessions_course_id"))

    op.drop_table("study_sessions")
    with op.batch_alter_table("quizzes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_quizzes_created_at"))
        batch_op.drop_index(batch_op.f("ix_quizzes_course_id"))

    op.drop_table("quizzes")
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_documents_status"))
        batch_op.drop_index(batch_op.f("ix_documents_sha256"))
        batch_op.drop_index(batch_op.f("ix_documents_created_at"))
        batch_op.drop_index(batch_op.f("ix_documents_course_id"))

    op.drop_table("documents")
    with op.batch_alter_table("courses", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_courses_name"))
        batch_op.drop_index(batch_op.f("ix_courses_created_at"))
        batch_op.drop_index(batch_op.f("ix_courses_archived_at"))

    op.drop_table("courses")
    # ### end Alembic commands ###
